feat(component): new file-input component
themesberg/flowbite-vue pull request #166
Opened 2023-07-07 00:54 UTC by vasucp1207

- File upload example
- Helper text
- Sizes
- Dropone

2023-07-07 08:07 UTC, cogor commented
May you add an empty line at end of file?
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2023-07-08 10:24 UTC, cogor commented
Drop zone doesn't work, can we fix it?
I found an article on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop) and think it will be heplful

2023-07-08 11:38 UTC, vasucp1207 commented
It's actually working but the value does not appear in dropzone, I fix this now it's working fine.

2023-07-10 18:26 UTC, cogor commented
Incorrect title in docs – "Vue Dropdown - Flowbite "

2023-07-10 18:30 UTC, cogor commented
And drag and drop files isn't works yet
[Look this video](https://imgur.com/a/ociuYVS), when I droped file it just opens in tab

2023-07-11 00:39 UTC, vasucp1207 commented
> And drag and drop files isn't works yet [Look this video](https://imgur.com/a/ociuYVS), when I droped file it just opens in tab

Fix the file drag part according to the MDN check now.

2023-07-14 11:41 UTC, cogor requested changes

2023-07-14 11:43 UTC, cogor commented
I found some problems: 
Instead of file I got filename and I can't do something with it, for example upload to server
We need to add multiple files support

2023-07-15 11:53 UTC, cogor commented on src/components/FileInput/FileInput.vue
> +  console.log('File(s) dropped')
```suggestion
```

2023-07-15 16:07 UTC, vasucp1207 commented
> I found some problems: Instead of file I got filename and I can't do something with it, for example upload to server We need to add multiple files support

Add support for multiple files, also changes file type to actual **file** object, not fileName.

2023-07-15 17:04 UTC, cogor approved these changes

2023-07-15 17:05 UTC, merged

2023-07-15 17:05 UTC, cogor commented
LGTM