Added HTML attribute: accept in FwbFileInput
themesberg/flowbite-vue pull request #278
Opened 2024-03-23 04:20 UTC by gitamgadtaula

The input file type component was missing native html attribute accept so in this commit i have included that. So now the users can use it something like  `<fwb-file-input v-model="file" label="Upload file" accept="video/*"  />`

2024-04-25 14:33 UTC, Sqrcz approved these changes
good catch, Thank You!

2024-04-26 14:27 UTC, Sqrcz requested changes
Hey @gitamgadtaula  I've just noticed... there is another `input` field on line 49... please add it there as well.

2024-04-27 02:20 UTC, gitamgadtaula commented
@Sqrcz Oh how could I have missed that one too. Anyway I added it and should be good to go now.

2024-04-29 08:15 UTC, Tomek-N approved these changes
Thanks!

2024-04-29 12:02 UTC, Sqrcz approved these changes
✅ Thank you!

2024-04-29 12:10 UTC, merged