Add basic modal component (Issue #56)
themesberg/flowbite-vue pull request #78
Opened 2022-08-31 17:48 UTC by Dmitri-2

Adds a basic version of the modal component. This component will still need additional updates to align with the functionality of the main Flowbite modal component. This first version implements the functions: 
- show
- hide 
- toggle

2022-09-19 09:30 UTC, cogor requested changes

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalExample.vue
> +    type: String, // 'bottom-left' | 'bottom-right' | 'bottom-center' | 'top-left' | 'top-center' | 'top-right' | 'center-left' | 'center' | 'center-right'
You need to extract this to type like [here](https://github.com/themesberg/flowbite-vue/blob/main/src/components/Avatar/types.ts)

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalExample.vue
> +    type: String, // 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl'
You need to extract this to type

2022-09-19 09:30 UTC, cogor commented on src/components/Modal/Modal.vue
> +    <slot name="trigger" :show="showModal" :hide="hideModal" :toggle="toggleModal"></slot>
You can use [self-closing component](https://v2.vuejs.org/v2/style-guide/?redirect=true#Self-closing-components-strongly-recommended)

2022-09-19 09:30 UTC, cogor commented on src/components/Modal/Modal.vue
> +            <slot name="header" :show="showModal" :hide="hideModal" :toggle="toggleModal"></slot>
```suggestion
            <slot name="header" :show="showModal" :hide="hideModal" :toggle="toggleModal" />
```

2022-09-19 09:30 UTC, cogor commented on src/components/Modal/Modal.vue
> +    <slot name="trigger" :show="showModal" :hide="hideModal" :toggle="toggleModal"></slot>
```suggestion
    <slot name="trigger" :show="showModal" :hide="hideModal" :toggle="toggleModal" />
```

2022-09-19 09:30 UTC, cogor commented on src/components/Modal/Modal.vue
> +            <slot name="body" :show="showModal" :hide="hideModal" :toggle="toggleModal"></slot>
```suggestion
            <slot name="body" :show="showModal" :hide="hideModal" :toggle="toggleModal" />
```

2022-09-19 09:30 UTC, cogor commented on src/components/Modal/Modal.vue
> +            <slot name="footer"  :show="showModal" :hide="hideModal" :toggle="toggleModal"/>
```suggestion
            <slot name="footer"  :show="showModal" :hide="hideModal" :toggle="toggleModal" />
```

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalSizeExample.vue
> +      <ModalExample size="xs" trigger-text="XS Modal"/>
```suggestion
      <ModalExample size="xs" trigger-text="XS Modal" />
```

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalSizeExample.vue
> +      <ModalExample size="md" trigger-text="MD Modal"/>
```suggestion
      <ModalExample size="md" trigger-text="MD Modal" />
```

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalSizeExample.vue
> +      <ModalExample size="xl" trigger-text="XL Modal"/>
```suggestion
      <ModalExample size="xl" trigger-text="XL Modal" />
```

2022-09-19 09:30 UTC, cogor commented on docs/components/modal/examples/ModalSizeExample.vue
> +      <ModalExample size="5xl" trigger-text="5XL Modal"/>
```suggestion
      <ModalExample size="5xl" trigger-text="5XL Modal" />
```

2022-09-19 09:31 UTC, cogor commented
Thanks for your PR, can you fix issues, which I found?

2022-10-03 00:26 UTC, Dmitri-2 commented
Yes! Sorry about the delay – PR is now updated.

2022-10-07 13:45 UTC, merged

2022-10-07 13:45 UTC, cogor commented
Thank you!